package ricm3.game.automaton;

public enum TypeCondition {
	OBSTACLE, CLOSEST, FREE, TRUE, KEYPRESSEDUP, KEYPRESSEDDOWN, KEYPRESSEDLEFT, KEYPRESSEDRIGHT, KEYPRESSEDNONE, KEYPRESSEDHIT, KEYPRESSEDPOP, KEYPRESSEDZ, KEYPRESSEDS, KEYPRESSEDQ, KEYPRESSEDD, KEYPRESSEDG, KEYPRESSEDF,KEYPRESSEDO,KEYPRESSEDI;
}
