package ricm3.game.automaton;

public enum TypeCondition {
	MYDIR, CLOSEST, CELL, TRUE, KEYPRESSEDZ, KEYPRESSEDQ, KEYPRESSEDS, KEYPRESSEDD, KEYPRESSEDO, KEYPRESSEDK, KEYPRESSEDL, KEYPRESSEDM, KEYPRESSEDA, KEYPRESSEDE, KEYPRESSEDF, KEYPRESSEDV, KEYPRESSEDC, KEYPRESSEDP, KEYPRESSEDI, KEYPRESSEDJ, KEYPRESSEDN, KEYPRESSEDCOMMA, KEYPRESSEDOTHER, KEYPRESSEDNONE;
}
